### PR TITLE
Fix empty select value attribute

### LINKED ISSUE #103: `SelectElement` does not render empty `value` attribute
This causes the browser to send the label as value.

### PR DESCRIPTION
**Pull request by nilmerg**
fixes #103

### CODE REVIEW

**Review by yhabteab — DISMISSED** [review]
LFTM!

**Comment by nilmerg** [comment]
I removed the return type hint from `getValueAttribute`. Please approve again, functionality didn't change.

**Review by yhabteab — APPROVED** [review]

**Comment by lippserd** [comment]
> I removed the return type hint from `getValueAttribute`. Please approve again, functionality didn't change.

Why? How does it ever return `mixed`?

**Comment by nilmerg** [comment]
Because https://github.com/Icinga/ipl-html/blob/master/src/FormElement/BaseFormElement.php#L323 and https://github.com/Icinga/ipl-html/blob/master/src/Attributes.php#L415-L422

**Comment by lippserd** [comment]
But this method here does not return `mixed`.

**Pull request merged**
