### PR TITLE
Streamline form validation

### PR DESCRIPTION
**Pull request by nilmerg**
Do yourself a favor and look at the commits individually including their descriptions :wink:

### CODE REVIEW

**Review by lippserd — CHANGES_REQUESTED** [review]
I would not change the validator chain yet. Everything else is perfectly fine.

**Comment by nilmerg** [comment]
What is your opinion on?: https://github.com/Icinga/ipl-html/pull/117/commits/17db370f4c3adb71041a377b278cbb9e2c79dfb0

**Comment by lippserd** [comment]
> What is your opinion on?: [17db370](https://github.com/Icinga/ipl-html/commit/17db370f4c3adb71041a377b278cbb9e2c79dfb0)

Feel free to remove it.

**Comment by nilmerg** [comment]
I've updated it. Noticed that there is no test which verifies that disabled options are invalid.

**Comment by lippserd** [comment]
> I've updated it. Noticed that there is no test which verifies that disabled options are invalid.

Yep, now I see it too 😆

**Review by lippserd — DISMISSED** [review]

**Review by lippserd — APPROVED** [review]

**Pull request merged**
