### PR TITLE
HtmlDocument::addFrom()

### PR DESCRIPTION
**Pull request by nilmerg**
Example usage:

```php
$columns->addFrom($hostStats, function (BaseHtmlElement $item) {
    $item->getAttributes()->add(['class' => 'col']);
    $item->setTag('div');
    return $item;
});
```

### CODE REVIEW

**Comment by Thomas-Gelf** [comment]
@nilmerg: `Html::wrapEach()` could be what you're looking for:

```php
$columns->add(Html::wrapEach($hostStats, function ($key, $value) {
    // ...
}));
```

**Comment by nilmerg** [comment]
Nope, I don't want another document layer. I simply need an approach to get items from one container and add them to another one while being able to transform them in the process.

e.g. this (the ul is `$hostStats`)
```html
<ul>
    <li>...</li>
    <li>...</li>
</ul>
```

to this: (the div is `$columns`)
```html
<div>
      <div>...</div>
      <div>...</div>
</div>
```

`wrapEach` doesn't allow me to do this in the same manner as `addFrom` does it. It also feels hacky using it for the intended effect.

**Comment by lippserd** [comment]
I'd like to see tests and maybe a section about this method in our docs.
And I'm not quite sure whether PHP optimizes the code but since we're trying to be as performant as possible with this lib, the check for the callback should be outside of the foreach.

**Comment by nilmerg** [comment]
Done.

**Pull request merged**
